### ISSUE TITLE
Добавить новую страницу с базовой разметкой и пустым body, назвать её styleguide.html

### ISSUE THREAD

**Issue by devlato** [arturican/arturican.study.devlato.com#2]
Что должно быть сделано:
- [x] Страница создана
- [x] Код страницы проходит [валидацию на W3C](https://validator.w3.org) с подтверждающим скриншотом
- [x] Страница запушена в репозиторий в отдельную ветку для код ревью
- [x] В репозитории настроен [GitHub Pages](https://pages.github.com)
- [x] Страница выложена на [GitHub Pages](https://pages.github.com) и доступна по [ссылке](https://arturican.github.io/arturican.study.devlato.com)

**Comment by arturican** [comment]
@devlato   `Страница запушена в репозиторий в отдельную ветку для код ревью` делаем новую ветку,  какое лучше назвать ветку?

**Comment by devlato** [comment]
@arturican Назови как хочешь) но с нормальным именем и следуй правилам. Типа feature/что-нибудь, bugfix/что-нибудь и т.д.

**Comment by devlato** [comment]
@arturican Например, так: https://gist.github.com/revett/88ee5abf5a9a097b4c88

**Comment by devlato** [comment]
@arturican Или так: https://github.com/snphq/guidelines/blob/master/standards/gitflow.md

**Comment by devlato** [comment]
https://arturican.github.io/arturican.study.devlato.com/styleguide.html

**Comment by arturican** [comment]
![image](https://user-images.githubusercontent.com/11317783/36642065-c0b489c6-1a4a-11e8-9a11-ce98444c3a69.png)
@devlato тогда этот блок заданий выполнен?

**Comment by devlato** [comment]
👍

**Comment by devlato** [comment]
@arturican Создавай пулл реквест этой ветки в мастер

**Comment by arturican** [comment]
@devlato  я переименовал  styleguide.html в index.html и чот нихуя не работает. `@arturican Создавай пулл реквест этой ветки в мастер` да пересоздал. Проверь пожалуйста

**Comment by devlato** [comment]
@arturican Потому что твой `index.html` в папке `html`

**Comment by arturican** [comment]
@devlato  как я сам не догадался
